### ISSUE TITLE
Ebon Gargoyle can sometimes have cast delays

### ISSUE THREAD

**Issue by BanterDK** [boukx/wotlk-death-knight#12]
**Game Version:**
3.4.0 Beta Build 44301

**Description:**
Summon Gargoyle's Construct, Ebon Gargoyle may sometimes have a slight delay in-between casts

**Details:**
Summon Gargoyle's Construct, Ebon Gargoyle may sometimes have a slight delay in-between casts, seemingly for no reason. There are a few observations so far:

- It does not seem to be related to melee range. While if the cast is cancelled, Gargoyle may instead melee the target, this is also seen at range as seen [here](https://clips.twitch.tv/CarefulFantasticMeatloafTBCheesePull-hB8VG4nWy8AwZGU1) 

 - Gargoyle may seemingly melee instead of cast. This may happen once, or several times, as seen [here ](https://drive.google.com/file/d/1wT0yrtOCbiwOGnvpRKhRzLhs69xmagaH/view?usp=sharing)

This seems to be related/similar to an issue that retail Dark Arbiter/Gargoyle had for a few years, and had several fixed implemented during Legion (more details will be posted regarding this)

**Reproduction rate:**
Seemingly always at random intervals

**Comment by BanterDK** [comment]
Evidence of several oddities within these [logs](https://classic.warcraftlogs.com/reports/JpFtN8nk1W6TH3xq/#fight=1&type=casts&view=events&source=5) recorded by Bouk (courtesy of Char)

I put the data in a spreadsheet to highlight the main issues here (see attached), and will update this post with the relevant vod (somewhere in [here](https://www.twitch.tv/videos/1511161156)

![image](https://user-images.githubusercontent.com/25447367/175256895-73716689-2bfa-44ed-828a-eabe8bb1f506.png)

**Comment by CharWS** [comment]
Here's the relevant video clip to match the log: https://clips.twitch.tv/GoldenIcyHareBibleThump-l_yVv0QYeeDTJRaR

**Comment by CharWS** [comment]
Found some relevant historical videos to add some more context here: https://youtu.be/F77MvbsLbxg?t=105 https://youtu.be/3eV85bRnxMk?t=153 https://youtu.be/BYK6OkFwbv8?t=550 (timestamped to what I see as the most useful sections, but there are multiple gargoyle uses in each)

**Comment by CharWS** [comment]
Appears to be fixed as of Beta Build: 3.4.0.44644
