### ISSUE TITLE
DK Pet UI covers Rune UI

### ISSUE THREAD

**Issue by BanterDK** [boukx/wotlk-death-knight#13]
**Game Version:**
3.4.0 Build 44301

**Description:**
DK Pet UI is anchored on top of the rune UI/directly beneath the player portrait, as opposed to beneath the rune UI

[WotLK reference footage ](https://youtu.be/_sCuBYdra_s?t=176) + [BG footage](https://youtu.be/BYK6OkFwbv8?t=296)
Image from WotLK Classic (Version as above) -- see attached 
![image](https://user-images.githubusercontent.com/25447367/175249846-e4b87434-9089-436f-9ff8-8cb2459e1d26.png)

**Comment by Aggrend** [comment]
We have a fix for this that did not quite make this week's beta build but should be present sometime after Tuesday 7/5's build.

**Comment by CharWS** [comment]
Fixed as of 3.4.0 (44729)
