### ISSUE TITLE
Killing Machine procs on offhand weapon hits

### ISSUE THREAD

**Issue by caccavale** [boukx/wotlk-death-knight#15]
**Game Version:**
3.4.0 Alpha Build 44301

**Description:**
Killing Machine procs on offhand weapon hits.  Expected behavior from old EJ posts suggest it just procs on mainhand

**Details:**
![image](https://user-images.githubusercontent.com/6198074/175327564-36a2a4c3-03d0-482a-8180-c1ccbb123441.png)

**Reproduction rate:**
Frequently

**Comment by caccavale** [comment]
![IUQSixPqSoSZYqhP2wd4vQ (2)](https://user-images.githubusercontent.com/6198074/175327766-a3896d42-1866-4243-bd5d-1b54b4c48d6d.png)

**Comment by caccavale** [comment]
Second glance, the talent specifies melee attacks so this may have been from unarmed main hand.  Needs more testing

**Comment by Aggrend** [comment]
According to our testing offhand procs are in fact disabled, and this lines up with the spell script. We aren't able to actually reproduce this behavior internally at all. Do you have links to logs or any other info that could help here? Thanks!

**Comment by CharWS** [comment]
Our mistake in testing actually on this one, we were getting procs from unarmed main hand strikes that threw us off. Gonna close it out and thanks for confirmation too
