### ISSUE TITLE
Talented Ghoul attacking a target dummy does not put player in combat

### ISSUE THREAD

**Issue by caccavale** [boukx/wotlk-death-knight#20]
**Game Version:**
3.4.0 Build 44301

**Description:**
> Briefly describe your bug (can be same as issue title).

**Details:**
> Explain your bug, preferably in detail

**Images, Videos, Logs**
> Please attach/link to any relevant videos, images or logs of the bug, if possible.

**Howto:**
> How do you reproduce it (if you know)? Numbered steps are ideal here.

**Reproduction rate:**
> Examples: 100%, sometimes, randomly

**Comment by JamminL** [comment]
Atleast for PVP, pets dont put you in combat. I'm not sure how a training dummy acts

**Comment by caccavale** [comment]
Understood.  Talented ghoul doesn't put the player in PvE either right now which does not align with how hunter pets work.

**Comment by Aggrend** [comment]
Confirmed with our designer that this is, in fact, Not A Bug.

**Comment by CharWS** [comment]
Excellent, thanks for confirmation
