### ISSUE TITLE
Duration of Mark of Blood is ~8s rather than 20 stated on tooltip when cast in PvP

### ISSUE THREAD

**Issue by caccavale** [boukx/wotlk-death-knight#22]
**Game Version:**
3.4.0 Build 44301

**Description:**
Duration of Mark of Blood is ~8s rather than 20 stated on tooltip.

**Howto:**
Cast Mark of Blood, start a timer

**Reproduction rate:**
100%

**Comment by JamminL** [comment]
https://youtu.be/VzG1RSb7vTU?t=52 NAB
