### ISSUE TITLE
Blood Tap does not work as expected.

### ISSUE THREAD

**Issue by caccavale** [boukx/wotlk-death-knight#6]
Using Blood Tap with 1 death on cooldown and 1 blood up converts the blood to death.
Using Blood Tap with 1 death and 1 blood both on cooldown converts the blood rune to death.

In neither case does it refresh any rune CDs

**Comment by Jeff425** [comment]
I think the bug is on the UI when a death rune is activated.

Try casting blood strike twice, use blood tap, then cast blood strike again.
It will let you cast even though all blood/death runes appear to be on CD

**Comment by Aggrend** [comment]
There's a few sort of bug-of-a-bug type issues with Death runes in general but I *think* most of the issues with Blood Tap should be resolved in the next build (any build put on beta after 44301)

**Comment by CharWS** [comment]
As of Beta Build 3.4.0.44547 Blood Tap appears to be functioning as expected
