### ISSUE TITLE
Proc Black Magic not incurring its iCD when equipped

### ISSUE THREAD

**Issue by caccavale** [boukx/wotlk-death-knight#7]
During combat you can swap to a weapon with Black Magic and it is off CD.  Our understanding is swapping to a weapon with Black Magic should put the proc on its internal cooldown.

**Comment by Cleavis** [comment]
expected behavior per 3.2.0 patch notes

https://gist.github.com/BradBlondebeard/51de640accc78e63e87a4e6d0ee73783#file-wotlkpatchnotes-txt-L2089

>    * Items with Triggered Effects: These items generally have cooldowns on how often they can be triggered. 
     Those cooldowns are now triggered each time the item is equipped (example: A trinket has a 45-second cooldown on an effect triggered by player attacks; when a player equips that item, the effect will be unable to be triggered for the 
       first 45 seconds it is worn).
