### ISSUE TITLE
Number of Blood Worms spawned seems tied to session

### ISSUE THREAD

**Issue by caccavale** [boukx/wotlk-death-knight#9]
A character with Blood Worms talent will spawn the same number of Blood Worms every time they proc in a single game session.  Once they log out and back in, a (potentially) different number will spawn each time it is proc'd that play session.

Steps to reproduce:
Talent it, proc it many times, you will get the same number of worms.
Relog, repeat, you will get a consistent number of worms per proc that may be different to your previous session.

**Comment by BanterDK** [comment]
Fairly vague title, could we rename for clarity?

**Comment by CharWS** [comment]
Want to look more into their proc mechanics, whether they're considered targets for multi target heals, and see if they parry haste enemies, + a bit on their scaling

**Comment by Bigmike4470** [comment]
worms

**Comment by caccavale** [comment]
A character with Blood Worms talent will spawn the same number of Blood Worms every time they proc in a single game session.  Once they log out and back in, a (potentially) different number will spawn each time it is proc'd that play session.

Steps to reproduce:
Talent it, proc it many times, you will get the same number of worms.
Relog, repeat, you will get a consistent number of worms per proc that may be different to your previous session.

**Comment by Aggrend** [comment]
This should be resolved as of build 44547.
